version: '3.8'

services:
  # Telegram Bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date +%Y%m%d_%H%M%S)}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    container_name: okdesk_bot
    command: python bot.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OKDESK_API_URL=${OKDESK_API_URL}
      - OKDESK_API_TOKEN=${OKDESK_API_TOKEN}
      - OKDESK_PORTAL_URL=${OKDESK_PORTAL_URL}
      - DATABASE_URL=sqlite:////app/data/okdesk_bot.db
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PATH=/okdesk-webhook
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - BUILD_DATE=${BUILD_DATE}
      - GIT_COMMIT=${GIT_COMMIT}
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    depends_on:
      - webhook
    networks:
      - okdesk_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://webhook:8000/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Webhook Server
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date +%Y%m%d_%H%M%S)}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    container_name: okdesk_webhook
    command: python webhook_server.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OKDESK_API_URL=${OKDESK_API_URL}
      - OKDESK_API_TOKEN=${OKDESK_API_TOKEN}
      - OKDESK_PORTAL_URL=${OKDESK_PORTAL_URL}
      - DATABASE_URL=sqlite:////app/data/okdesk_bot.db
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PATH=/okdesk-webhook
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - HOST=0.0.0.0
      - PORT=8000
      - BUILD_DATE=${BUILD_DATE}
      - GIT_COMMIT=${GIT_COMMIT}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    networks:
      - okdesk_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  okdesk_network:
    driver: bridge

volumes:
  okdesk_data:
