version: '3.8'

services:
  # Telegram Bot
  bot:
    build: .
    container_name: okdesk_bot
    command: python bot.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OKDESK_API_URL=${OKDESK_API_URL}
      - OKDESK_API_TOKEN=${OKDESK_API_TOKEN}
      - DATABASE_URL=sqlite:////app/data/okdesk_bot.db
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PATH=/okdesk-webhook
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - webhook
    networks:
      - okdesk_network

  # Webhook Server
  webhook:
    build: .
    container_name: okdesk_webhook
    command: python webhook_server.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OKDESK_API_URL=${OKDESK_API_URL}
      - OKDESK_API_TOKEN=${OKDESK_API_TOKEN}
      - DATABASE_URL=sqlite:////app/data/okdesk_bot.db
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PATH=/okdesk-webhook
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - okdesk_network

networks:
  okdesk_network:
    driver: bridge

volumes:
  okdesk_data:
